// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CardIssueReason string

const (
	CardIssueReasonAnswer     CardIssueReason = "answer"
	CardIssueReasonWording    CardIssueReason = "wording"
	CardIssueReasonNotInNotes CardIssueReason = "not-in-notes"
	CardIssueReasonOther      CardIssueReason = "other"
)

func (e *CardIssueReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CardIssueReason(s)
	case string:
		*e = CardIssueReason(s)
	default:
		return fmt.Errorf("unsupported scan type for CardIssueReason: %T", src)
	}
	return nil
}

type NullCardIssueReason struct {
	CardIssueReason CardIssueReason `json:"card_issue_reason"`
	Valid           bool            `json:"valid"` // Valid is true if CardIssueReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCardIssueReason) Scan(value interface{}) error {
	if value == nil {
		ns.CardIssueReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CardIssueReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCardIssueReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CardIssueReason), nil
}

type CardKind string

const (
	CardKindChoice  CardKind = "choice"
	CardKindFlip    CardKind = "flip"
	CardKindInput   CardKind = "input"
	CardKindBoolean CardKind = "boolean"
	CardKindTable   CardKind = "table"
)

func (e *CardKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CardKind(s)
	case string:
		*e = CardKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CardKind: %T", src)
	}
	return nil
}

type NullCardKind struct {
	CardKind CardKind `json:"card_kind"`
	Valid    bool     `json:"valid"` // Valid is true if CardKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCardKind) Scan(value interface{}) error {
	if value == nil {
		ns.CardKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CardKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCardKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CardKind), nil
}

type Card struct {
	ID                pgtype.UUID        `json:"id"`
	SetID             pgtype.UUID        `json:"set_id"`
	Kind              CardKind           `json:"kind"`
	Question          string             `json:"question"`
	AnswerChoiceIndex pgtype.Int4        `json:"answer_choice_index"`
	AnswerText        pgtype.Text        `json:"answer_text"`
	AnswerBoolean     pgtype.Bool        `json:"answer_boolean"`
	Explanation       string             `json:"explanation"`
	SourceQuote       string             `json:"source_quote"`
	SourceRef         pgtype.Text        `json:"source_ref"`
	Topic             string             `json:"topic"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type CardIssue struct {
	ID        int64              `json:"id"`
	CardID    pgtype.UUID        `json:"card_id"`
	UserID    int64              `json:"user_id"`
	Reason    CardIssueReason    `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CardOption struct {
	ID          int64       `json:"id"`
	CardID      pgtype.UUID `json:"card_id"`
	OptionIndex int32       `json:"option_index"`
	Text        string      `json:"text"`
}

type CardReview struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	CardID     pgtype.UUID        `json:"card_id"`
	Correct    bool               `json:"correct"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

type CardSet struct {
	ID        pgtype.UUID        `json:"id"`
	CreatorID int64              `json:"creator_id"`
	Title     string             `json:"title"`
	ShareCode string             `json:"share_code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CardTableColumn struct {
	ID          int64       `json:"id"`
	CardID      pgtype.UUID `json:"card_id"`
	ColumnIndex int32       `json:"column_index"`
	Title       string      `json:"title"`
}

type CardTableItem struct {
	ID       int64       `json:"id"`
	CardID   pgtype.UUID `json:"card_id"`
	ColumnID int64       `json:"column_id"`
	Text     string      `json:"text"`
}

type User struct {
	ID        int64              `json:"id"`
	Username  pgtype.Text        `json:"username"`
	FirstName pgtype.Text        `json:"first_name"`
	LastName  pgtype.Text        `json:"last_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserCardProgress struct {
	UserID         int64              `json:"user_id"`
	CardID         pgtype.UUID        `json:"card_id"`
	NextReviewAt   pgtype.Timestamptz `json:"next_review_at"`
	LastReviewedAt pgtype.Timestamptz `json:"last_reviewed_at"`
	Repetitions    int32              `json:"repetitions"`
	IntervalDays   int32              `json:"interval_days"`
}

type UserCardSet struct {
	UserID   int64              `json:"user_id"`
	SetID    pgtype.UUID        `json:"set_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}
