// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDueCardsCountByUserID = `-- name: GetDueCardsCountByUserID :one
SELECT COUNT(DISTINCT c.id)::int AS due_count
FROM cards c
JOIN card_sets s ON s.id = c.set_id
LEFT JOIN user_card_sets ucs ON ucs.set_id = s.id AND ucs.user_id = $1
JOIN user_card_progress p ON p.card_id = c.id AND p.user_id = $1
WHERE (s.creator_id = $1 OR ucs.user_id = $1)
  AND p.next_review_at <= now()
`

func (q *Queries) GetDueCardsCountByUserID(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getDueCardsCountByUserID, userID)
	var due_count int32
	err := row.Scan(&due_count)
	return due_count, err
}

const getFeedCardsByUserID = `-- name: GetFeedCardsByUserID :many
SELECT c.id, c.set_id, c.kind, c.question, c.answer_choice_index, c.answer_text, c.answer_boolean, c.explanation, c.source_quote, c.source_ref, c.topic, c.created_at, c.updated_at
FROM cards c
JOIN card_sets s ON s.id = c.set_id
LEFT JOIN user_card_sets ucs ON ucs.set_id = s.id AND ucs.user_id = $1
LEFT JOIN user_card_progress p ON p.card_id = c.id AND p.user_id = $1
WHERE (s.creator_id = $1 OR ucs.user_id = $1)
  AND (p.next_review_at IS NULL OR p.next_review_at <= now())
ORDER BY COALESCE(p.next_review_at, now()) ASC
LIMIT $2
`

type GetFeedCardsByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetFeedCardsByUserID(ctx context.Context, arg GetFeedCardsByUserIDParams) ([]Card, error) {
	rows, err := q.db.Query(ctx, getFeedCardsByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.SetID,
			&i.Kind,
			&i.Question,
			&i.AnswerChoiceIndex,
			&i.AnswerText,
			&i.AnswerBoolean,
			&i.Explanation,
			&i.SourceQuote,
			&i.SourceRef,
			&i.Topic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetPlanBySetID = `-- name: GetSetPlanBySetID :many
SELECT 
    c.topic AS fact_name,
    COALESCE(p.next_review_at, now()) AS review_date
FROM cards c
LEFT JOIN user_card_progress p ON p.card_id = c.id AND p.user_id = $2
WHERE c.set_id = $1
ORDER BY review_date ASC
`

type GetSetPlanBySetIDParams struct {
	SetID  pgtype.UUID `json:"set_id"`
	UserID int64       `json:"user_id"`
}

type GetSetPlanBySetIDRow struct {
	FactName   string             `json:"fact_name"`
	ReviewDate pgtype.Timestamptz `json:"review_date"`
}

func (q *Queries) GetSetPlanBySetID(ctx context.Context, arg GetSetPlanBySetIDParams) ([]GetSetPlanBySetIDRow, error) {
	rows, err := q.db.Query(ctx, getSetPlanBySetID, arg.SetID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSetPlanBySetIDRow
	for rows.Next() {
		var i GetSetPlanBySetIDRow
		if err := rows.Scan(&i.FactName, &i.ReviewDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCardReview = `-- name: RecordCardReview :one
INSERT INTO card_reviews (user_id, card_id, correct, answered_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, card_id, correct, answered_at
`

type RecordCardReviewParams struct {
	UserID     int64              `json:"user_id"`
	CardID     pgtype.UUID        `json:"card_id"`
	Correct    bool               `json:"correct"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

func (q *Queries) RecordCardReview(ctx context.Context, arg RecordCardReviewParams) (CardReview, error) {
	row := q.db.QueryRow(ctx, recordCardReview,
		arg.UserID,
		arg.CardID,
		arg.Correct,
		arg.AnsweredAt,
	)
	var i CardReview
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.Correct,
		&i.AnsweredAt,
	)
	return i, err
}

const upsertCardProgress = `-- name: UpsertCardProgress :one
INSERT INTO user_card_progress (
    user_id,
    card_id,
    next_review_at,
    last_reviewed_at,
    repetitions,
    interval_days
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id, card_id) DO UPDATE
SET next_review_at = EXCLUDED.next_review_at,
    last_reviewed_at = EXCLUDED.last_reviewed_at,
    repetitions = EXCLUDED.repetitions,
    interval_days = EXCLUDED.interval_days
RETURNING user_id, card_id, next_review_at, last_reviewed_at, repetitions, interval_days
`

type UpsertCardProgressParams struct {
	UserID         int64              `json:"user_id"`
	CardID         pgtype.UUID        `json:"card_id"`
	NextReviewAt   pgtype.Timestamptz `json:"next_review_at"`
	LastReviewedAt pgtype.Timestamptz `json:"last_reviewed_at"`
	Repetitions    int32              `json:"repetitions"`
	IntervalDays   int32              `json:"interval_days"`
}

func (q *Queries) UpsertCardProgress(ctx context.Context, arg UpsertCardProgressParams) (UserCardProgress, error) {
	row := q.db.QueryRow(ctx, upsertCardProgress,
		arg.UserID,
		arg.CardID,
		arg.NextReviewAt,
		arg.LastReviewedAt,
		arg.Repetitions,
		arg.IntervalDays,
	)
	var i UserCardProgress
	err := row.Scan(
		&i.UserID,
		&i.CardID,
		&i.NextReviewAt,
		&i.LastReviewedAt,
		&i.Repetitions,
		&i.IntervalDays,
	)
	return i, err
}
