// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSet = `-- name: CreateSet :one
INSERT INTO card_sets (creator_id, title, share_code)
VALUES ($1, $2, $3)
RETURNING id, creator_id, title, share_code, created_at, updated_at
`

type CreateSetParams struct {
	CreatorID int64  `json:"creator_id"`
	Title     string `json:"title"`
	ShareCode string `json:"share_code"`
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (CardSet, error) {
	row := q.db.QueryRow(ctx, createSet, arg.CreatorID, arg.Title, arg.ShareCode)
	var i CardSet
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.ShareCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSetByID = `-- name: DeleteSetByID :exec
DELETE FROM card_sets
WHERE id = $1 AND creator_id = $2
`

type DeleteSetByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	CreatorID int64       `json:"creator_id"`
}

func (q *Queries) DeleteSetByID(ctx context.Context, arg DeleteSetByIDParams) error {
	_, err := q.db.Exec(ctx, deleteSetByID, arg.ID, arg.CreatorID)
	return err
}

const getSetByID = `-- name: GetSetByID :one
SELECT 
    s.id,
    s.creator_id,
    s.title,
    s.share_code,
    s.created_at,
    s.updated_at,
    u.first_name AS author_name,
    COUNT(DISTINCT c.id)::int AS cards_total,
    COUNT(DISTINCT CASE WHEN p.next_review_at <= now() THEN c.id END)::int AS cards_due
FROM card_sets s
JOIN users u ON u.id = s.creator_id
LEFT JOIN cards c ON c.set_id = s.id
LEFT JOIN user_card_progress p ON p.card_id = c.id AND p.user_id = $2
WHERE s.id = $1
GROUP BY s.id, s.creator_id, s.title, s.share_code, s.created_at, s.updated_at, u.first_name
`

type GetSetByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID int64       `json:"user_id"`
}

type GetSetByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	CreatorID  int64              `json:"creator_id"`
	Title      string             `json:"title"`
	ShareCode  string             `json:"share_code"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	AuthorName pgtype.Text        `json:"author_name"`
	CardsTotal int32              `json:"cards_total"`
	CardsDue   int32              `json:"cards_due"`
}

func (q *Queries) GetSetByID(ctx context.Context, arg GetSetByIDParams) (GetSetByIDRow, error) {
	row := q.db.QueryRow(ctx, getSetByID, arg.ID, arg.UserID)
	var i GetSetByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.ShareCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.CardsTotal,
		&i.CardsDue,
	)
	return i, err
}

const getSetByShareCode = `-- name: GetSetByShareCode :one
SELECT id, creator_id, title, share_code, created_at, updated_at
FROM card_sets
WHERE share_code = $1
`

func (q *Queries) GetSetByShareCode(ctx context.Context, shareCode string) (CardSet, error) {
	row := q.db.QueryRow(ctx, getSetByShareCode, shareCode)
	var i CardSet
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.ShareCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const joinSet = `-- name: JoinSet :exec
INSERT INTO user_card_sets (user_id, set_id)
VALUES ($1, $2)
ON CONFLICT (user_id, set_id) DO NOTHING
`

type JoinSetParams struct {
	UserID int64       `json:"user_id"`
	SetID  pgtype.UUID `json:"set_id"`
}

func (q *Queries) JoinSet(ctx context.Context, arg JoinSetParams) error {
	_, err := q.db.Exec(ctx, joinSet, arg.UserID, arg.SetID)
	return err
}

const leaveSet = `-- name: LeaveSet :exec
DELETE FROM user_card_sets
WHERE user_id = $1 AND set_id = $2
`

type LeaveSetParams struct {
	UserID int64       `json:"user_id"`
	SetID  pgtype.UUID `json:"set_id"`
}

func (q *Queries) LeaveSet(ctx context.Context, arg LeaveSetParams) error {
	_, err := q.db.Exec(ctx, leaveSet, arg.UserID, arg.SetID)
	return err
}

const listSetsByUserID = `-- name: ListSetsByUserID :many
SELECT 
    s.id,
    s.creator_id,
    s.title,
    s.share_code,
    CASE WHEN s.creator_id != $1 THEN u.first_name ELSE '' END AS author_name,
    COUNT(DISTINCT c.id)::int AS cards_total,
    COUNT(DISTINCT CASE WHEN p.next_review_at <= now() THEN c.id END)::int AS cards_due
FROM card_sets s
JOIN users u ON u.id = s.creator_id
LEFT JOIN user_card_sets ucs ON ucs.set_id = s.id AND ucs.user_id = $1
LEFT JOIN cards c ON c.set_id = s.id
LEFT JOIN user_card_progress p ON p.card_id = c.id AND p.user_id = $1
WHERE s.creator_id = $1 OR ucs.user_id = $1
GROUP BY s.id, s.creator_id, s.title, s.share_code, s.created_at, u.first_name
ORDER BY s.created_at DESC
`

type ListSetsByUserIDRow struct {
	ID         pgtype.UUID `json:"id"`
	CreatorID  int64       `json:"creator_id"`
	Title      string      `json:"title"`
	ShareCode  string      `json:"share_code"`
	AuthorName string      `json:"author_name"`
	CardsTotal int32       `json:"cards_total"`
	CardsDue   int32       `json:"cards_due"`
}

func (q *Queries) ListSetsByUserID(ctx context.Context, creatorID int64) ([]ListSetsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listSetsByUserID, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSetsByUserIDRow
	for rows.Next() {
		var i ListSetsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.ShareCode,
			&i.AuthorName,
			&i.CardsTotal,
			&i.CardsDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
