version: '3'

tasks:
  lint:
    desc: 'Проверка кода бэкенда (golangci-lint)'
    cmds:
      - golangci-lint run ./...

  test:
    desc: 'Запуск тестов бэкенда'
    cmds:
      - go test -v ./...

  build:
    desc: 'Сборка бинарника бэкенда'
    cmds:
      - go build -o server ./cmd/server

  sqlc:
    desc: 'Генерация Go-кода по SQL-запросам (sqlc)'
    aliases:
      - gen
      - gen:sql
    sources:
      - sqlc.yaml
      - repository/migrations/*.sql
      - repository/migrations/**/*.sql
      - repository/queries/*.sql
      - repository/queries/**/*.sql
    generates:
      - repository/db/*.go
      - repository/db/**/*.go
    cmds:
      - sqlc generate
