// Code generated by ogen, DO NOT EDIT.

package contracts

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AnswerQuestionParams is parameters of AnswerQuestion operation.
type AnswerQuestionParams struct {
	// The ID of the card.
	CardId uuid.UUID
}

func unpackAnswerQuestionParams(packed middleware.Parameters) (params AnswerQuestionParams) {
	{
		key := middleware.ParameterKey{
			Name: "cardId",
			In:   "path",
		}
		params.CardId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAnswerQuestionParams(args [1]string, argsEscaped bool, r *http.Request) (params AnswerQuestionParams, _ error) {
	// Decode path: cardId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cardId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CardId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cardId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CheckAnswerParams is parameters of CheckAnswer operation.
type CheckAnswerParams struct {
	// The ID of the card.
	CardId uuid.UUID
}

func unpackCheckAnswerParams(packed middleware.Parameters) (params CheckAnswerParams) {
	{
		key := middleware.ParameterKey{
			Name: "cardId",
			In:   "path",
		}
		params.CardId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCheckAnswerParams(args [1]string, argsEscaped bool, r *http.Request) (params CheckAnswerParams, _ error) {
	// Decode path: cardId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cardId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CardId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cardId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteCardParams is parameters of DeleteCard operation.
type DeleteCardParams struct {
	// The ID of the card to delete.
	CardId uuid.UUID
}

func unpackDeleteCardParams(packed middleware.Parameters) (params DeleteCardParams) {
	{
		key := middleware.ParameterKey{
			Name: "cardId",
			In:   "path",
		}
		params.CardId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteCardParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteCardParams, _ error) {
	// Decode path: cardId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cardId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CardId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cardId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteSetParams is parameters of DeleteSet operation.
type DeleteSetParams struct {
	// The ID of the card set to delete.
	SetId uuid.UUID
}

func unpackDeleteSetParams(packed middleware.Parameters) (params DeleteSetParams) {
	{
		key := middleware.ParameterKey{
			Name: "setId",
			In:   "path",
		}
		params.SetId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteSetParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteSetParams, _ error) {
	// Decode path: setId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "setId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SetId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "setId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetCardsBySetIDParams is parameters of GetCardsBySetID operation.
type GetCardsBySetIDParams struct {
	// Filter cards by set ID.
	SetId uuid.UUID
}

func unpackGetCardsBySetIDParams(packed middleware.Parameters) (params GetCardsBySetIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "setId",
			In:   "path",
		}
		params.SetId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetCardsBySetIDParams(args [1]string, argsEscaped bool, r *http.Request) (params GetCardsBySetIDParams, _ error) {
	// Decode path: setId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "setId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SetId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "setId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetSetParams is parameters of GetSet operation.
type GetSetParams struct {
	// The ID of the card set.
	SetId uuid.UUID
}

func unpackGetSetParams(packed middleware.Parameters) (params GetSetParams) {
	{
		key := middleware.ParameterKey{
			Name: "setId",
			In:   "path",
		}
		params.SetId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetSetParams(args [1]string, argsEscaped bool, r *http.Request) (params GetSetParams, _ error) {
	// Decode path: setId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "setId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SetId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "setId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetSetLeaderboardParams is parameters of GetSetLeaderboard operation.
type GetSetLeaderboardParams struct {
	// The ID of the card set.
	SetId uuid.UUID
}

func unpackGetSetLeaderboardParams(packed middleware.Parameters) (params GetSetLeaderboardParams) {
	{
		key := middleware.ParameterKey{
			Name: "setId",
			In:   "path",
		}
		params.SetId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetSetLeaderboardParams(args [1]string, argsEscaped bool, r *http.Request) (params GetSetLeaderboardParams, _ error) {
	// Decode path: setId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "setId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SetId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "setId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetSetPlanParams is parameters of GetSetPlan operation.
type GetSetPlanParams struct {
	SetId uuid.UUID
}

func unpackGetSetPlanParams(packed middleware.Parameters) (params GetSetPlanParams) {
	{
		key := middleware.ParameterKey{
			Name: "setId",
			In:   "path",
		}
		params.SetId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetSetPlanParams(args [1]string, argsEscaped bool, r *http.Request) (params GetSetPlanParams, _ error) {
	// Decode path: setId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "setId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SetId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "setId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetSetShareCodeParams is parameters of GetSetShareCode operation.
type GetSetShareCodeParams struct {
	// The ID of the card set.
	SetId uuid.UUID
}

func unpackGetSetShareCodeParams(packed middleware.Parameters) (params GetSetShareCodeParams) {
	{
		key := middleware.ParameterKey{
			Name: "setId",
			In:   "path",
		}
		params.SetId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetSetShareCodeParams(args [1]string, argsEscaped bool, r *http.Request) (params GetSetShareCodeParams, _ error) {
	// Decode path: setId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "setId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.SetId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "setId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ReportCardIssueParams is parameters of ReportCardIssue operation.
type ReportCardIssueParams struct {
	// The ID of the card.
	CardId uuid.UUID
}

func unpackReportCardIssueParams(packed middleware.Parameters) (params ReportCardIssueParams) {
	{
		key := middleware.ParameterKey{
			Name: "cardId",
			In:   "path",
		}
		params.CardId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeReportCardIssueParams(args [1]string, argsEscaped bool, r *http.Request) (params ReportCardIssueParams, _ error) {
	// Decode path: cardId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cardId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CardId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cardId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateCardParams is parameters of UpdateCard operation.
type UpdateCardParams struct {
	// The ID of the card to update.
	CardId uuid.UUID
}

func unpackUpdateCardParams(packed middleware.Parameters) (params UpdateCardParams) {
	{
		key := middleware.ParameterKey{
			Name: "cardId",
			In:   "path",
		}
		params.CardId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateCardParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateCardParams, _ error) {
	// Decode path: cardId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cardId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CardId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cardId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
