// Code generated by ogen, DO NOT EDIT.

package contracts

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHealth implements getHealth operation.
//
// Health check endpoint.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *HealthResponse, _ error) {
	return r, ht.ErrNotImplemented
}
