// Code generated by ogen, DO NOT EDIT.

package contracts

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AnswerQuestion implements AnswerQuestion operation.
	//
	// Send answer's text for input kind of questions.
	//
	// POST /cards/{cardId}/answer
	AnswerQuestion(ctx context.Context, req *AnswerQuestionRequest, params AnswerQuestionParams) (AnswerQuestionRes, error)
	// CheckAnswer implements CheckAnswer operation.
	//
	// The answer need not match word for word: form, word order and typos do not matter, and answers in
	// other words are judged by a language model. Nothing is recorded: the feed sends results with
	// SendResults.
	//
	// POST /cards/{cardId}/check
	CheckAnswer(ctx context.Context, req *CheckAnswerRequest, params CheckAnswerParams) (CheckAnswerRes, error)
	// DeleteCard implements DeleteCard operation.
	//
	// Delete a card.
	//
	// DELETE /cards/{cardId}
	DeleteCard(ctx context.Context, params DeleteCardParams) (DeleteCardRes, error)
	// DeleteSet implements DeleteSet operation.
	//
	// Delete a card set.
	//
	// DELETE /sets/{setId}
	DeleteSet(ctx context.Context, params DeleteSetParams) (DeleteSetRes, error)
	// GetCardsBySetID implements GetCardsBySetID operation.
	//
	// Get cards.
	//
	// GET /sets/{setId}/cards
	GetCardsBySetID(ctx context.Context, params GetCardsBySetIDParams) (GetCardsBySetIDRes, error)
	// GetFeedQuestions implements GetFeedQuestions operation.
	//
	// Get questions of current feed.
	//
	// GET /feed
	GetFeedQuestions(ctx context.Context) (GetFeedQuestionsRes, error)
	// GetHealth implements getHealth operation.
	//
	// Health check endpoint.
	//
	// GET /health
	GetHealth(ctx context.Context) (GetHealthRes, error)
	// GetSet implements GetSet operation.
	//
	// Get a card set.
	//
	// GET /sets/{setId}
	GetSet(ctx context.Context, params GetSetParams) (GetSetRes, error)
	// GetSetLeaderboard implements GetSetLeaderboard operation.
	//
	// Get set leaderboard for author.
	//
	// GET /sets/{setId}/leaderboard
	GetSetLeaderboard(ctx context.Context, params GetSetLeaderboardParams) (GetSetLeaderboardRes, error)
	// GetSetPlan implements GetSetPlan operation.
	//
	// Get set's facts plan.
	//
	// GET /sets/{setId}/plan
	GetSetPlan(ctx context.Context, params GetSetPlanParams) (GetSetPlanRes, error)
	// GetSetShareCode implements GetSetShareCode operation.
	//
	// Get share code for a set.
	//
	// GET /sets/{setId}/share
	GetSetShareCode(ctx context.Context, params GetSetShareCodeParams) (GetSetShareCodeRes, error)
	// GetToday implements GetToday operation.
	//
	// Get today overview data.
	//
	// GET /
	GetToday(ctx context.Context) (GetTodayRes, error)
	// JoinSetByShareCode implements JoinSetByShareCode operation.
	//
	// Join a card set by code.
	//
	// POST /sets/join
	JoinSetByShareCode(ctx context.Context, req *JoinSetRequest) (JoinSetByShareCodeRes, error)
	// ReportCardIssue implements ReportCardIssue operation.
	//
	// Report an issue with a card.
	//
	// POST /cards/{cardId}/issue
	ReportCardIssue(ctx context.Context, req *ReportCardIssueRequest, params ReportCardIssueParams) (ReportCardIssueRes, error)
	// SendResults implements SendResults operation.
	//
	// Send set/feed results.
	//
	// POST /results
	SendResults(ctx context.Context, req SendResultsRequest) (SendResultsRes, error)
	// UpdateCard implements UpdateCard operation.
	//
	// Update a card.
	//
	// PUT /cards/{cardId}
	UpdateCard(ctx context.Context, req *UpdateCardRequest, params UpdateCardParams) (UpdateCardRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
