// Code generated by ogen, DO NOT EDIT.
package contracts

type AnswerQuestionRes interface {
	answerQuestionRes()
}

type DeleteCardRes interface {
	deleteCardRes()
}

type DeleteSetRes interface {
	deleteSetRes()
}

type GetCardsBySetIDRes interface {
	getCardsBySetIDRes()
}

type GetFeedQuestionsRes interface {
	getFeedQuestionsRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type GetSetLeaderboardRes interface {
	getSetLeaderboardRes()
}

type GetSetPlanRes interface {
	getSetPlanRes()
}

type GetSetRes interface {
	getSetRes()
}

type GetSetShareCodeRes interface {
	getSetShareCodeRes()
}

type GetTodayRes interface {
	getTodayRes()
}

type JoinSetByShareCodeRes interface {
	joinSetByShareCodeRes()
}

type ReportCardIssueRes interface {
	reportCardIssueRes()
}

type SendResultsRes interface {
	sendResultsRes()
}

type UpdateCardRes interface {
	updateCardRes()
}
