// Code generated by ogen, DO NOT EDIT.

package contracts

// OperationName is the ogen operation name
type OperationName = string

const (
	AnswerQuestionOperation     OperationName = "AnswerQuestion"
	DeleteCardOperation         OperationName = "DeleteCard"
	DeleteSetOperation          OperationName = "DeleteSet"
	GetCardsBySetIDOperation    OperationName = "GetCardsBySetID"
	GetFeedQuestionsOperation   OperationName = "GetFeedQuestions"
	GetHealthOperation          OperationName = "GetHealth"
	GetSetOperation             OperationName = "GetSet"
	GetSetLeaderboardOperation  OperationName = "GetSetLeaderboard"
	GetSetPlanOperation         OperationName = "GetSetPlan"
	GetSetShareCodeOperation    OperationName = "GetSetShareCode"
	GetTodayOperation           OperationName = "GetToday"
	JoinSetByShareCodeOperation OperationName = "JoinSetByShareCode"
	ReportCardIssueOperation    OperationName = "ReportCardIssue"
	SendResultsOperation        OperationName = "SendResults"
	UpdateCardOperation         OperationName = "UpdateCard"
)
