// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (id, fact_id, kind, question, answer_text, explanation, source_quote, source_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, fact_id, kind, question, answer_text, explanation, source_quote, source_ref, created_at, updated_at
`

type CreateCardParams struct {
	ID          pgtype.UUID `json:"id"`
	FactID      string      `json:"fact_id"`
	Kind        string      `json:"kind"`
	Question    string      `json:"question"`
	AnswerText  pgtype.Text `json:"answer_text"`
	Explanation string      `json:"explanation"`
	SourceQuote string      `json:"source_quote"`
	SourceRef   pgtype.Text `json:"source_ref"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ID,
		arg.FactID,
		arg.Kind,
		arg.Question,
		arg.AnswerText,
		arg.Explanation,
		arg.SourceQuote,
		arg.SourceRef,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.FactID,
		&i.Kind,
		&i.Question,
		&i.AnswerText,
		&i.Explanation,
		&i.SourceQuote,
		&i.SourceRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCardOption = `-- name: CreateCardOption :one
INSERT INTO card_options (card_id, position, text, is_correct)
VALUES ($1, $2, $3, $4)
RETURNING id, card_id, position, text, is_correct
`

type CreateCardOptionParams struct {
	CardID    pgtype.UUID `json:"card_id"`
	Position  int32       `json:"position"`
	Text      string      `json:"text"`
	IsCorrect bool        `json:"is_correct"`
}

func (q *Queries) CreateCardOption(ctx context.Context, arg CreateCardOptionParams) (CardOption, error) {
	row := q.db.QueryRow(ctx, createCardOption,
		arg.CardID,
		arg.Position,
		arg.Text,
		arg.IsCorrect,
	)
	var i CardOption
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Position,
		&i.Text,
		&i.IsCorrect,
	)
	return i, err
}

const createCardTableColumn = `-- name: CreateCardTableColumn :one
INSERT INTO card_table_columns (card_id, position, name)
VALUES ($1, $2, $3)
RETURNING id, card_id, position, name
`

type CreateCardTableColumnParams struct {
	CardID   pgtype.UUID `json:"card_id"`
	Position int32       `json:"position"`
	Name     string      `json:"name"`
}

func (q *Queries) CreateCardTableColumn(ctx context.Context, arg CreateCardTableColumnParams) (CardTableColumn, error) {
	row := q.db.QueryRow(ctx, createCardTableColumn, arg.CardID, arg.Position, arg.Name)
	var i CardTableColumn
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Position,
		&i.Name,
	)
	return i, err
}

const createCardTableItem = `-- name: CreateCardTableItem :one
INSERT INTO card_table_items (card_id, item_text, column_name)
VALUES ($1, $2, $3)
RETURNING id, card_id, item_text, column_name
`

type CreateCardTableItemParams struct {
	CardID     pgtype.UUID `json:"card_id"`
	ItemText   string      `json:"item_text"`
	ColumnName string      `json:"column_name"`
}

func (q *Queries) CreateCardTableItem(ctx context.Context, arg CreateCardTableItemParams) (CardTableItem, error) {
	row := q.db.QueryRow(ctx, createCardTableItem, arg.CardID, arg.ItemText, arg.ColumnName)
	var i CardTableItem
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ItemText,
		&i.ColumnName,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :execrows
DELETE FROM cards c
USING facts f, sets s
WHERE c.id = $1
  AND c.fact_id = f.id
  AND f.set_id = s.id
  AND s.author_id = $2
`

type DeleteCardParams struct {
	ID       pgtype.UUID `json:"id"`
	AuthorID int64       `json:"author_id"`
}

func (q *Queries) DeleteCard(ctx context.Context, arg DeleteCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCard, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCardOptions = `-- name: DeleteCardOptions :exec
DELETE FROM card_options WHERE card_id = $1
`

func (q *Queries) DeleteCardOptions(ctx context.Context, cardID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCardOptions, cardID)
	return err
}

const deleteCardTableColumns = `-- name: DeleteCardTableColumns :exec
DELETE FROM card_table_columns WHERE card_id = $1
`

func (q *Queries) DeleteCardTableColumns(ctx context.Context, cardID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCardTableColumns, cardID)
	return err
}

const deleteCardTableItems = `-- name: DeleteCardTableItems :exec
DELETE FROM card_table_items WHERE card_id = $1
`

func (q *Queries) DeleteCardTableItems(ctx context.Context, cardID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCardTableItems, cardID)
	return err
}

const getCardByID = `-- name: GetCardByID :one
SELECT
    c.id,
    f.set_id,
    c.fact_id,
    c.kind,
    ck.difficulty_level,
    c.question,
    c.answer_text,
    c.explanation,
    c.source_quote,
    c.source_ref,
    COALESCE(t.name, '') AS topic,
    c.created_at,
    c.updated_at
FROM cards c
JOIN facts f ON c.fact_id = f.id
JOIN card_kinds ck ON c.kind = ck.kind
LEFT JOIN topics t ON f.topic_id = t.id
WHERE c.id = $1
  AND EXISTS (
      SELECT 1 FROM sets s
      WHERE s.id = f.set_id
        AND (s.author_id = $2 OR EXISTS (SELECT 1 FROM user_sets us WHERE us.set_id = s.id AND us.user_id = $2))
  )
`

type GetCardByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID int64       `json:"user_id"`
}

type GetCardByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	SetID           pgtype.UUID        `json:"set_id"`
	FactID          string             `json:"fact_id"`
	Kind            string             `json:"kind"`
	DifficultyLevel int16              `json:"difficulty_level"`
	Question        string             `json:"question"`
	AnswerText      pgtype.Text        `json:"answer_text"`
	Explanation     string             `json:"explanation"`
	SourceQuote     string             `json:"source_quote"`
	SourceRef       pgtype.Text        `json:"source_ref"`
	Topic           string             `json:"topic"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCardByID(ctx context.Context, arg GetCardByIDParams) (GetCardByIDRow, error) {
	row := q.db.QueryRow(ctx, getCardByID, arg.ID, arg.UserID)
	var i GetCardByIDRow
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.FactID,
		&i.Kind,
		&i.DifficultyLevel,
		&i.Question,
		&i.AnswerText,
		&i.Explanation,
		&i.SourceQuote,
		&i.SourceRef,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardByIDForAuthor = `-- name: GetCardByIDForAuthor :one
SELECT
    c.id,
    f.set_id,
    c.fact_id,
    c.kind,
    ck.difficulty_level,
    c.question,
    c.answer_text,
    c.explanation,
    c.source_quote,
    c.source_ref,
    COALESCE(t.name, '') AS topic,
    c.created_at,
    c.updated_at
FROM cards c
JOIN facts f ON c.fact_id = f.id
JOIN card_kinds ck ON c.kind = ck.kind
LEFT JOIN topics t ON f.topic_id = t.id
JOIN sets s ON f.set_id = s.id
WHERE c.id = $1 AND s.author_id = $2
`

type GetCardByIDForAuthorParams struct {
	ID       pgtype.UUID `json:"id"`
	AuthorID int64       `json:"author_id"`
}

type GetCardByIDForAuthorRow struct {
	ID              pgtype.UUID        `json:"id"`
	SetID           pgtype.UUID        `json:"set_id"`
	FactID          string             `json:"fact_id"`
	Kind            string             `json:"kind"`
	DifficultyLevel int16              `json:"difficulty_level"`
	Question        string             `json:"question"`
	AnswerText      pgtype.Text        `json:"answer_text"`
	Explanation     string             `json:"explanation"`
	SourceQuote     string             `json:"source_quote"`
	SourceRef       pgtype.Text        `json:"source_ref"`
	Topic           string             `json:"topic"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCardByIDForAuthor(ctx context.Context, arg GetCardByIDForAuthorParams) (GetCardByIDForAuthorRow, error) {
	row := q.db.QueryRow(ctx, getCardByIDForAuthor, arg.ID, arg.AuthorID)
	var i GetCardByIDForAuthorRow
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.FactID,
		&i.Kind,
		&i.DifficultyLevel,
		&i.Question,
		&i.AnswerText,
		&i.Explanation,
		&i.SourceQuote,
		&i.SourceRef,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardOptions = `-- name: GetCardOptions :many
SELECT id, card_id, position, text, is_correct
FROM card_options
WHERE card_id = $1
ORDER BY position ASC
`

func (q *Queries) GetCardOptions(ctx context.Context, cardID pgtype.UUID) ([]CardOption, error) {
	rows, err := q.db.Query(ctx, getCardOptions, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardOption
	for rows.Next() {
		var i CardOption
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Position,
			&i.Text,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardTableColumns = `-- name: GetCardTableColumns :many
SELECT id, card_id, position, name
FROM card_table_columns
WHERE card_id = $1
ORDER BY position ASC
`

func (q *Queries) GetCardTableColumns(ctx context.Context, cardID pgtype.UUID) ([]CardTableColumn, error) {
	rows, err := q.db.Query(ctx, getCardTableColumns, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardTableColumn
	for rows.Next() {
		var i CardTableColumn
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Position,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardTableItems = `-- name: GetCardTableItems :many
SELECT id, card_id, item_text, column_name
FROM card_table_items
WHERE card_id = $1
`

func (q *Queries) GetCardTableItems(ctx context.Context, cardID pgtype.UUID) ([]CardTableItem, error) {
	rows, err := q.db.Query(ctx, getCardTableItems, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardTableItem
	for rows.Next() {
		var i CardTableItem
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ItemText,
			&i.ColumnName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardsBySetID = `-- name: GetCardsBySetID :many
SELECT
    c.id,
    f.set_id,
    c.fact_id,
    c.kind,
    ck.difficulty_level,
    c.question,
    c.answer_text,
    c.explanation,
    c.source_quote,
    c.source_ref,
    COALESCE(t.name, '') AS topic,
    c.created_at,
    c.updated_at
FROM cards c
JOIN facts f ON c.fact_id = f.id
JOIN card_kinds ck ON c.kind = ck.kind
LEFT JOIN topics t ON f.topic_id = t.id
WHERE f.set_id = $1
  AND EXISTS (
      SELECT 1 FROM sets s
      WHERE s.id = $1
        AND (s.author_id = $2 OR EXISTS (SELECT 1 FROM user_sets us WHERE us.set_id = s.id AND us.user_id = $2))
  )
ORDER BY c.created_at ASC
`

type GetCardsBySetIDParams struct {
	SetID  pgtype.UUID `json:"set_id"`
	UserID int64       `json:"user_id"`
}

type GetCardsBySetIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	SetID           pgtype.UUID        `json:"set_id"`
	FactID          string             `json:"fact_id"`
	Kind            string             `json:"kind"`
	DifficultyLevel int16              `json:"difficulty_level"`
	Question        string             `json:"question"`
	AnswerText      pgtype.Text        `json:"answer_text"`
	Explanation     string             `json:"explanation"`
	SourceQuote     string             `json:"source_quote"`
	SourceRef       pgtype.Text        `json:"source_ref"`
	Topic           string             `json:"topic"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCardsBySetID(ctx context.Context, arg GetCardsBySetIDParams) ([]GetCardsBySetIDRow, error) {
	rows, err := q.db.Query(ctx, getCardsBySetID, arg.SetID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCardsBySetIDRow
	for rows.Next() {
		var i GetCardsBySetIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SetID,
			&i.FactID,
			&i.Kind,
			&i.DifficultyLevel,
			&i.Question,
			&i.AnswerText,
			&i.Explanation,
			&i.SourceQuote,
			&i.SourceRef,
			&i.Topic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedCardsForUser = `-- name: GetFeedCardsForUser :many
WITH user_due_facts AS (
    SELECT
        f.id AS fact_id,
        f.set_id,
        COALESCE(t.name, '') AS topic,
        COALESCE(ufp.elo, 700) AS elo,
        CASE
            WHEN COALESCE(ufp.elo, 700) < 800 THEN 0
            WHEN COALESCE(ufp.elo, 700) < 1000 THEN 1
            WHEN COALESCE(ufp.elo, 700) < 1200 THEN 2
            WHEN COALESCE(ufp.elo, 700) < 1400 THEN 3
            ELSE 4
        END AS target_difficulty
    FROM user_sets us
    JOIN facts f ON us.set_id = f.set_id
    LEFT JOIN topics t ON f.topic_id = t.id
    LEFT JOIN user_fact_progress ufp ON ufp.fact_id = f.id AND ufp.user_id = us.user_id
    WHERE us.user_id = $1
      AND (ufp.next_review_at IS NULL OR ufp.next_review_at <= NOW())
),
ranked_cards AS (
    SELECT
        c.id,
        udf.set_id,
        c.fact_id,
        c.kind,
        ck.difficulty_level,
        c.question,
        c.answer_text,
        c.explanation,
        c.source_quote,
        c.source_ref,
        udf.topic,
        c.created_at,
        c.updated_at,
        ROW_NUMBER() OVER (
            PARTITION BY c.fact_id
            ORDER BY ABS(ck.difficulty_level - udf.target_difficulty) ASC, c.created_at ASC
        ) AS rank
    FROM cards c
    JOIN user_due_facts udf ON c.fact_id = udf.fact_id
    JOIN card_kinds ck ON c.kind = ck.kind
)
SELECT
    id,
    set_id,
    fact_id,
    kind,
    difficulty_level,
    question,
    answer_text,
    explanation,
    source_quote,
    source_ref,
    topic,
    created_at,
    updated_at
FROM ranked_cards
WHERE rank = 1
`

type GetFeedCardsForUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	SetID           pgtype.UUID        `json:"set_id"`
	FactID          string             `json:"fact_id"`
	Kind            string             `json:"kind"`
	DifficultyLevel int16              `json:"difficulty_level"`
	Question        string             `json:"question"`
	AnswerText      pgtype.Text        `json:"answer_text"`
	Explanation     string             `json:"explanation"`
	SourceQuote     string             `json:"source_quote"`
	SourceRef       pgtype.Text        `json:"source_ref"`
	Topic           string             `json:"topic"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFeedCardsForUser(ctx context.Context, userID int64) ([]GetFeedCardsForUserRow, error) {
	rows, err := q.db.Query(ctx, getFeedCardsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedCardsForUserRow
	for rows.Next() {
		var i GetFeedCardsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.SetID,
			&i.FactID,
			&i.Kind,
			&i.DifficultyLevel,
			&i.Question,
			&i.AnswerText,
			&i.Explanation,
			&i.SourceQuote,
			&i.SourceRef,
			&i.Topic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET
    kind = COALESCE($2, kind),
    question = COALESCE($3, question),
    answer_text = COALESCE($4, answer_text),
    explanation = COALESCE($5, explanation),
    source_quote = COALESCE($6, source_quote),
    source_ref = COALESCE($7, source_ref),
    updated_at = CURRENT_TIMESTAMP
FROM facts f
JOIN sets s ON f.set_id = s.id
WHERE cards.id = $1
  AND cards.fact_id = f.id
  AND s.author_id = $8
RETURNING cards.id, cards.fact_id, cards.kind, cards.question, cards.answer_text, cards.explanation, cards.source_quote, cards.source_ref, cards.created_at, cards.updated_at
`

type UpdateCardParams struct {
	ID          pgtype.UUID `json:"id"`
	Kind        string      `json:"kind"`
	Question    string      `json:"question"`
	AnswerText  pgtype.Text `json:"answer_text"`
	Explanation string      `json:"explanation"`
	SourceQuote string      `json:"source_quote"`
	SourceRef   pgtype.Text `json:"source_ref"`
	AuthorID    int64       `json:"author_id"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.ID,
		arg.Kind,
		arg.Question,
		arg.AnswerText,
		arg.Explanation,
		arg.SourceQuote,
		arg.SourceRef,
		arg.AuthorID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.FactID,
		&i.Kind,
		&i.Question,
		&i.AnswerText,
		&i.Explanation,
		&i.SourceQuote,
		&i.SourceRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
