// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (
    set_id,
    kind,
    question,
    answer_choice_index,
    answer_text,
    answer_boolean,
    explanation,
    source_quote,
    source_ref,
    topic
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, set_id, kind, question, answer_choice_index, answer_text, answer_boolean, explanation, source_quote, source_ref, topic, created_at, updated_at
`

type CreateCardParams struct {
	SetID             pgtype.UUID `json:"set_id"`
	Kind              CardKind    `json:"kind"`
	Question          string      `json:"question"`
	AnswerChoiceIndex pgtype.Int4 `json:"answer_choice_index"`
	AnswerText        pgtype.Text `json:"answer_text"`
	AnswerBoolean     pgtype.Bool `json:"answer_boolean"`
	Explanation       string      `json:"explanation"`
	SourceQuote       string      `json:"source_quote"`
	SourceRef         pgtype.Text `json:"source_ref"`
	Topic             string      `json:"topic"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.SetID,
		arg.Kind,
		arg.Question,
		arg.AnswerChoiceIndex,
		arg.AnswerText,
		arg.AnswerBoolean,
		arg.Explanation,
		arg.SourceQuote,
		arg.SourceRef,
		arg.Topic,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Kind,
		&i.Question,
		&i.AnswerChoiceIndex,
		&i.AnswerText,
		&i.AnswerBoolean,
		&i.Explanation,
		&i.SourceQuote,
		&i.SourceRef,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCardOption = `-- name: CreateCardOption :exec
INSERT INTO card_options (card_id, option_index, text)
VALUES ($1, $2, $3)
`

type CreateCardOptionParams struct {
	CardID      pgtype.UUID `json:"card_id"`
	OptionIndex int32       `json:"option_index"`
	Text        string      `json:"text"`
}

func (q *Queries) CreateCardOption(ctx context.Context, arg CreateCardOptionParams) error {
	_, err := q.db.Exec(ctx, createCardOption, arg.CardID, arg.OptionIndex, arg.Text)
	return err
}

const createCardTableColumn = `-- name: CreateCardTableColumn :one
INSERT INTO card_table_columns (card_id, column_index, title)
VALUES ($1, $2, $3)
RETURNING id, card_id, column_index, title
`

type CreateCardTableColumnParams struct {
	CardID      pgtype.UUID `json:"card_id"`
	ColumnIndex int32       `json:"column_index"`
	Title       string      `json:"title"`
}

func (q *Queries) CreateCardTableColumn(ctx context.Context, arg CreateCardTableColumnParams) (CardTableColumn, error) {
	row := q.db.QueryRow(ctx, createCardTableColumn, arg.CardID, arg.ColumnIndex, arg.Title)
	var i CardTableColumn
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ColumnIndex,
		&i.Title,
	)
	return i, err
}

const createCardTableItem = `-- name: CreateCardTableItem :exec
INSERT INTO card_table_items (card_id, column_id, text)
VALUES ($1, $2, $3)
`

type CreateCardTableItemParams struct {
	CardID   pgtype.UUID `json:"card_id"`
	ColumnID int64       `json:"column_id"`
	Text     string      `json:"text"`
}

func (q *Queries) CreateCardTableItem(ctx context.Context, arg CreateCardTableItemParams) error {
	_, err := q.db.Exec(ctx, createCardTableItem, arg.CardID, arg.ColumnID, arg.Text)
	return err
}

const deleteCardByID = `-- name: DeleteCardByID :exec
DELETE FROM cards
WHERE id = $1
`

func (q *Queries) DeleteCardByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCardByID, id)
	return err
}

const deleteCardOptionsByCardID = `-- name: DeleteCardOptionsByCardID :exec
DELETE FROM card_options
WHERE card_id = $1
`

func (q *Queries) DeleteCardOptionsByCardID(ctx context.Context, cardID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCardOptionsByCardID, cardID)
	return err
}

const deleteCardTableColumnsByCardID = `-- name: DeleteCardTableColumnsByCardID :exec
DELETE FROM card_table_columns
WHERE card_id = $1
`

func (q *Queries) DeleteCardTableColumnsByCardID(ctx context.Context, cardID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCardTableColumnsByCardID, cardID)
	return err
}

const getCardByID = `-- name: GetCardByID :one
SELECT id, set_id, kind, question, answer_choice_index, answer_text, answer_boolean, explanation, source_quote, source_ref, topic, created_at, updated_at
FROM cards
WHERE id = $1
`

func (q *Queries) GetCardByID(ctx context.Context, id pgtype.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Kind,
		&i.Question,
		&i.AnswerChoiceIndex,
		&i.AnswerText,
		&i.AnswerBoolean,
		&i.Explanation,
		&i.SourceQuote,
		&i.SourceRef,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardOptionsByCardID = `-- name: ListCardOptionsByCardID :many
SELECT id, card_id, option_index, text
FROM card_options
WHERE card_id = $1
ORDER BY option_index ASC
`

func (q *Queries) ListCardOptionsByCardID(ctx context.Context, cardID pgtype.UUID) ([]CardOption, error) {
	rows, err := q.db.Query(ctx, listCardOptionsByCardID, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardOption
	for rows.Next() {
		var i CardOption
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.OptionIndex,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardTableColumnsByCardID = `-- name: ListCardTableColumnsByCardID :many
SELECT id, card_id, column_index, title
FROM card_table_columns
WHERE card_id = $1
ORDER BY column_index ASC
`

func (q *Queries) ListCardTableColumnsByCardID(ctx context.Context, cardID pgtype.UUID) ([]CardTableColumn, error) {
	rows, err := q.db.Query(ctx, listCardTableColumnsByCardID, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardTableColumn
	for rows.Next() {
		var i CardTableColumn
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ColumnIndex,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardTableItemsByCardID = `-- name: ListCardTableItemsByCardID :many
SELECT 
    i.id,
    i.card_id,
    i.column_id,
    i.text,
    c.title AS column_title
FROM card_table_items i
JOIN card_table_columns c ON c.id = i.column_id
WHERE i.card_id = $1
ORDER BY i.id ASC
`

type ListCardTableItemsByCardIDRow struct {
	ID          int64       `json:"id"`
	CardID      pgtype.UUID `json:"card_id"`
	ColumnID    int64       `json:"column_id"`
	Text        string      `json:"text"`
	ColumnTitle string      `json:"column_title"`
}

func (q *Queries) ListCardTableItemsByCardID(ctx context.Context, cardID pgtype.UUID) ([]ListCardTableItemsByCardIDRow, error) {
	rows, err := q.db.Query(ctx, listCardTableItemsByCardID, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardTableItemsByCardIDRow
	for rows.Next() {
		var i ListCardTableItemsByCardIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ColumnID,
			&i.Text,
			&i.ColumnTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsBySetID = `-- name: ListCardsBySetID :many
SELECT id, set_id, kind, question, answer_choice_index, answer_text, answer_boolean, explanation, source_quote, source_ref, topic, created_at, updated_at
FROM cards c
JOIN card_sets s ON s.id = c.set_id
LEFT JOIN user_card_sets ucs ON ucs.set_id = s.id AND ucs.user_id = $2
WHERE c.set_id = $1
  AND (s.creator_id = $2 OR ucs.user_id = $2)
ORDER BY c.created_at ASC
`

type ListCardsBySetIDParams struct {
	SetID  pgtype.UUID `json:"set_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) ListCardsBySetID(ctx context.Context, arg ListCardsBySetIDParams) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCardsBySetID, arg.SetID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.SetID,
			&i.Kind,
			&i.Question,
			&i.AnswerChoiceIndex,
			&i.AnswerText,
			&i.AnswerBoolean,
			&i.Explanation,
			&i.SourceQuote,
			&i.SourceRef,
			&i.Topic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardByID = `-- name: UpdateCardByID :one
UPDATE cards
SET question = COALESCE($2, question),
    answer_choice_index = COALESCE($3, answer_choice_index),
    answer_text = COALESCE($4, answer_text),
    answer_boolean = COALESCE($5, answer_boolean),
    explanation = COALESCE($6, explanation),
    source_quote = COALESCE($7, source_quote),
    source_ref = COALESCE($8, source_ref),
    topic = COALESCE($9, topic),
    updated_at = now()
WHERE id = $1
RETURNING id, set_id, kind, question, answer_choice_index, answer_text, answer_boolean, explanation, source_quote, source_ref, topic, created_at, updated_at
`

type UpdateCardByIDParams struct {
	ID                pgtype.UUID `json:"id"`
	Question          string      `json:"question"`
	AnswerChoiceIndex pgtype.Int4 `json:"answer_choice_index"`
	AnswerText        pgtype.Text `json:"answer_text"`
	AnswerBoolean     pgtype.Bool `json:"answer_boolean"`
	Explanation       string      `json:"explanation"`
	SourceQuote       string      `json:"source_quote"`
	SourceRef         pgtype.Text `json:"source_ref"`
	Topic             string      `json:"topic"`
}

func (q *Queries) UpdateCardByID(ctx context.Context, arg UpdateCardByIDParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCardByID,
		arg.ID,
		arg.Question,
		arg.AnswerChoiceIndex,
		arg.AnswerText,
		arg.AnswerBoolean,
		arg.Explanation,
		arg.SourceQuote,
		arg.SourceRef,
		arg.Topic,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Kind,
		&i.Question,
		&i.AnswerChoiceIndex,
		&i.AnswerText,
		&i.AnswerBoolean,
		&i.Explanation,
		&i.SourceQuote,
		&i.SourceRef,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
