// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFact = `-- name: CreateFact :one
INSERT INTO facts (id, set_id, topic_id, name)
VALUES ($1, $2, $3, $4)
RETURNING id, set_id, topic_id, name, created_at
`

type CreateFactParams struct {
	ID      string      `json:"id"`
	SetID   pgtype.UUID `json:"set_id"`
	TopicID pgtype.UUID `json:"topic_id"`
	Name    string      `json:"name"`
}

func (q *Queries) CreateFact(ctx context.Context, arg CreateFactParams) (Fact, error) {
	row := q.db.QueryRow(ctx, createFact,
		arg.ID,
		arg.SetID,
		arg.TopicID,
		arg.Name,
	)
	var i Fact
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.TopicID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getFactsBySetID = `-- name: GetFactsBySetID :many
SELECT f.id, f.set_id, f.name, f.created_at, COALESCE(t.name, '') AS topic_name
FROM facts f
LEFT JOIN topics t ON f.topic_id = t.id
WHERE f.set_id = $1
ORDER BY f.created_at ASC
`

type GetFactsBySetIDRow struct {
	ID        string             `json:"id"`
	SetID     pgtype.UUID        `json:"set_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TopicName string             `json:"topic_name"`
}

func (q *Queries) GetFactsBySetID(ctx context.Context, setID pgtype.UUID) ([]GetFactsBySetIDRow, error) {
	rows, err := q.db.Query(ctx, getFactsBySetID, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFactsBySetIDRow
	for rows.Next() {
		var i GetFactsBySetIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SetID,
			&i.Name,
			&i.CreatedAt,
			&i.TopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetPlan = `-- name: GetSetPlan :many
SELECT
    f.name AS fact_name,
    COALESCE(ufp.next_review_at, CURRENT_TIMESTAMP) AS date
FROM facts f
LEFT JOIN user_fact_progress ufp ON ufp.fact_id = f.id AND ufp.user_id = $2
WHERE f.set_id = $1
  AND EXISTS (
      SELECT 1 FROM sets s
      WHERE s.id = $1
        AND (s.author_id = $2 OR EXISTS (SELECT 1 FROM user_sets us WHERE us.set_id = s.id AND us.user_id = $2))
  )
ORDER BY COALESCE(ufp.next_review_at, CURRENT_TIMESTAMP) ASC
`

type GetSetPlanParams struct {
	SetID  pgtype.UUID `json:"set_id"`
	UserID int64       `json:"user_id"`
}

type GetSetPlanRow struct {
	FactName string             `json:"fact_name"`
	Date     pgtype.Timestamptz `json:"date"`
}

func (q *Queries) GetSetPlan(ctx context.Context, arg GetSetPlanParams) ([]GetSetPlanRow, error) {
	rows, err := q.db.Query(ctx, getSetPlan, arg.SetID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSetPlanRow
	for rows.Next() {
		var i GetSetPlanRow
		if err := rows.Scan(&i.FactName, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFactProgress = `-- name: GetUserFactProgress :one
SELECT user_id, fact_id, elo, ceiling_found, consecutive_correct, consecutive_incorrect, interval_days, ease_factor, next_review_at, last_reviewed_at FROM user_fact_progress
WHERE user_id = $1 AND fact_id = $2
`

type GetUserFactProgressParams struct {
	UserID int64  `json:"user_id"`
	FactID string `json:"fact_id"`
}

func (q *Queries) GetUserFactProgress(ctx context.Context, arg GetUserFactProgressParams) (UserFactProgress, error) {
	row := q.db.QueryRow(ctx, getUserFactProgress, arg.UserID, arg.FactID)
	var i UserFactProgress
	err := row.Scan(
		&i.UserID,
		&i.FactID,
		&i.Elo,
		&i.CeilingFound,
		&i.ConsecutiveCorrect,
		&i.ConsecutiveIncorrect,
		&i.IntervalDays,
		&i.EaseFactor,
		&i.NextReviewAt,
		&i.LastReviewedAt,
	)
	return i, err
}

const initUserFactProgress = `-- name: InitUserFactProgress :exec
INSERT INTO user_fact_progress (user_id, fact_id, elo, ceiling_found, next_review_at)
SELECT $1, f.id, 700, FALSE, CURRENT_TIMESTAMP
FROM facts f
WHERE f.set_id = $2
ON CONFLICT (user_id, fact_id) DO NOTHING
`

type InitUserFactProgressParams struct {
	UserID int64       `json:"user_id"`
	SetID  pgtype.UUID `json:"set_id"`
}

func (q *Queries) InitUserFactProgress(ctx context.Context, arg InitUserFactProgressParams) error {
	_, err := q.db.Exec(ctx, initUserFactProgress, arg.UserID, arg.SetID)
	return err
}

const upsertTopic = `-- name: UpsertTopic :one
INSERT INTO topics (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

func (q *Queries) UpsertTopic(ctx context.Context, name string) (Topic, error) {
	row := q.db.QueryRow(ctx, upsertTopic, name)
	var i Topic
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
