// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCardIssue = `-- name: CreateCardIssue :one
INSERT INTO card_issues (card_id, user_id, reason)
VALUES ($1, $2, $3)
RETURNING id, card_id, user_id, reason, created_at
`

type CreateCardIssueParams struct {
	CardID pgtype.UUID     `json:"card_id"`
	UserID int64           `json:"user_id"`
	Reason CardIssueReason `json:"reason"`
}

func (q *Queries) CreateCardIssue(ctx context.Context, arg CreateCardIssueParams) (CardIssue, error) {
	row := q.db.QueryRow(ctx, createCardIssue, arg.CardID, arg.UserID, arg.Reason)
	var i CardIssue
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listCardIssuesByCardID = `-- name: ListCardIssuesByCardID :many
SELECT id, card_id, user_id, reason, created_at
FROM card_issues
WHERE card_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCardIssuesByCardID(ctx context.Context, cardID pgtype.UUID) ([]CardIssue, error) {
	rows, err := q.db.Query(ctx, listCardIssuesByCardID, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardIssue
	for rows.Next() {
		var i CardIssue
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.UserID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
