// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCardIssue = `-- name: CreateCardIssue :one
INSERT INTO card_issues (card_id, user_id, reason)
VALUES ($1, $2, $3)
RETURNING id, card_id, user_id, reason, created_at
`

type CreateCardIssueParams struct {
	CardID pgtype.UUID     `json:"card_id"`
	UserID int64           `json:"user_id"`
	Reason CardIssueReason `json:"reason"`
}

func (q *Queries) CreateCardIssue(ctx context.Context, arg CreateCardIssueParams) (CardIssue, error) {
	row := q.db.QueryRow(ctx, createCardIssue, arg.CardID, arg.UserID, arg.Reason)
	var i CardIssue
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}
