// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnswerResult struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     int64              `json:"user_id"`
	CardID     pgtype.UUID        `json:"card_id"`
	Correct    bool               `json:"correct"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Card struct {
	ID          pgtype.UUID        `json:"id"`
	FactID      string             `json:"fact_id"`
	Kind        string             `json:"kind"`
	Question    string             `json:"question"`
	AnswerText  pgtype.Text        `json:"answer_text"`
	Explanation string             `json:"explanation"`
	SourceQuote string             `json:"source_quote"`
	SourceRef   pgtype.Text        `json:"source_ref"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CardKind struct {
	Kind            string `json:"kind"`
	DifficultyLevel int16  `json:"difficulty_level"`
}

type CardOption struct {
	ID        pgtype.UUID `json:"id"`
	CardID    pgtype.UUID `json:"card_id"`
	Position  int32       `json:"position"`
	Text      string      `json:"text"`
	IsCorrect bool        `json:"is_correct"`
}

type CardTableColumn struct {
	ID       pgtype.UUID `json:"id"`
	CardID   pgtype.UUID `json:"card_id"`
	Position int32       `json:"position"`
	Name     string      `json:"name"`
}

type CardTableItem struct {
	ID         pgtype.UUID `json:"id"`
	CardID     pgtype.UUID `json:"card_id"`
	ItemText   string      `json:"item_text"`
	ColumnName string      `json:"column_name"`
}

type Fact struct {
	ID        string             `json:"id"`
	SetID     pgtype.UUID        `json:"set_id"`
	TopicID   pgtype.UUID        `json:"topic_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Set struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	AuthorID  int64              `json:"author_id"`
	ShareCode string             `json:"share_code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Topic struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	FirstName    string             `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	Username     pgtype.Text        `json:"username"`
	IsBot        bool               `json:"is_bot"`
}

type UserFactProgress struct {
	UserID               int64              `json:"user_id"`
	FactID               string             `json:"fact_id"`
	Elo                  int32              `json:"elo"`
	CeilingFound         bool               `json:"ceiling_found"`
	ConsecutiveCorrect   int32              `json:"consecutive_correct"`
	ConsecutiveIncorrect int32              `json:"consecutive_incorrect"`
	IntervalDays         int32              `json:"interval_days"`
	EaseFactor           pgtype.Numeric     `json:"ease_factor"`
	NextReviewAt         pgtype.Timestamptz `json:"next_review_at"`
	LastReviewedAt       pgtype.Timestamptz `json:"last_reviewed_at"`
}

type UserSet struct {
	UserID   int64              `json:"user_id"`
	SetID    pgtype.UUID        `json:"set_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}
