// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountTotalDueCardsForUser(ctx context.Context, userID int64) (int32, error)
	CountUserActiveDays(ctx context.Context, userID int64) (int32, error)
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	CreateCardIssue(ctx context.Context, arg CreateCardIssueParams) (CardIssue, error)
	CreateCardOption(ctx context.Context, arg CreateCardOptionParams) (CardOption, error)
	CreateCardTableColumn(ctx context.Context, arg CreateCardTableColumnParams) (CardTableColumn, error)
	CreateCardTableItem(ctx context.Context, arg CreateCardTableItemParams) (CardTableItem, error)
	CreateFact(ctx context.Context, arg CreateFactParams) (Fact, error)
	CreateSet(ctx context.Context, arg CreateSetParams) (Set, error)
	DeleteCard(ctx context.Context, arg DeleteCardParams) (int64, error)
	DeleteCardOptions(ctx context.Context, cardID pgtype.UUID) error
	DeleteCardTableColumns(ctx context.Context, cardID pgtype.UUID) error
	DeleteCardTableItems(ctx context.Context, cardID pgtype.UUID) error
	DeleteSet(ctx context.Context, arg DeleteSetParams) (int64, error)
	EnsureUser(ctx context.Context, id int64) (User, error)
	GetCardByID(ctx context.Context, arg GetCardByIDParams) (GetCardByIDRow, error)
	GetCardByIDForAuthor(ctx context.Context, arg GetCardByIDForAuthorParams) (GetCardByIDForAuthorRow, error)
	GetCardOptions(ctx context.Context, cardID pgtype.UUID) ([]CardOption, error)
	GetCardTableColumns(ctx context.Context, cardID pgtype.UUID) ([]CardTableColumn, error)
	GetCardTableItems(ctx context.Context, cardID pgtype.UUID) ([]CardTableItem, error)
	GetCardsBySetID(ctx context.Context, arg GetCardsBySetIDParams) ([]GetCardsBySetIDRow, error)
	GetFactsBySetID(ctx context.Context, setID pgtype.UUID) ([]GetFactsBySetIDRow, error)
	GetFeedCardsForUser(ctx context.Context, userID int64) ([]GetFeedCardsForUserRow, error)
	GetSetByID(ctx context.Context, arg GetSetByIDParams) (GetSetByIDRow, error)
	GetSetByShareCode(ctx context.Context, arg GetSetByShareCodeParams) (GetSetByShareCodeRow, error)
	GetSetPlan(ctx context.Context, arg GetSetPlanParams) ([]GetSetPlanRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserFactProgress(ctx context.Context, arg GetUserFactProgressParams) (UserFactProgress, error)
	GetUserSets(ctx context.Context, userID int64) ([]GetUserSetsRow, error)
	InitUserFactProgress(ctx context.Context, arg InitUserFactProgressParams) error
	IsSetAuthor(ctx context.Context, arg IsSetAuthorParams) (bool, error)
	JoinSet(ctx context.Context, arg JoinSetParams) (UserSet, error)
	LeaveSet(ctx context.Context, arg LeaveSetParams) (int64, error)
	RecordAnswerResult(ctx context.Context, arg RecordAnswerResultParams) (AnswerResult, error)
	UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error)
	UpdateFactProgressOnAnswer(ctx context.Context, arg UpdateFactProgressOnAnswerParams) (UserFactProgress, error)
	UpsertTopic(ctx context.Context, name string) (Topic, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
