// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	CreateCardIssue(ctx context.Context, arg CreateCardIssueParams) (CardIssue, error)
	CreateCardOption(ctx context.Context, arg CreateCardOptionParams) error
	CreateCardTableColumn(ctx context.Context, arg CreateCardTableColumnParams) (CardTableColumn, error)
	CreateCardTableItem(ctx context.Context, arg CreateCardTableItemParams) error
	CreateSet(ctx context.Context, arg CreateSetParams) (CardSet, error)
	DeleteCardByID(ctx context.Context, id pgtype.UUID) error
	DeleteCardOptionsByCardID(ctx context.Context, cardID pgtype.UUID) error
	DeleteCardTableColumnsByCardID(ctx context.Context, cardID pgtype.UUID) error
	DeleteSetByID(ctx context.Context, arg DeleteSetByIDParams) error
	GetCardByID(ctx context.Context, id pgtype.UUID) (Card, error)
	GetDueCardsCountByUserID(ctx context.Context, userID int64) (int32, error)
	GetFeedCardsByUserID(ctx context.Context, arg GetFeedCardsByUserIDParams) ([]Card, error)
	GetSetByID(ctx context.Context, arg GetSetByIDParams) (GetSetByIDRow, error)
	GetSetByShareCode(ctx context.Context, shareCode string) (CardSet, error)
	GetSetPlanBySetID(ctx context.Context, arg GetSetPlanBySetIDParams) ([]GetSetPlanBySetIDRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	JoinSet(ctx context.Context, arg JoinSetParams) error
	LeaveSet(ctx context.Context, arg LeaveSetParams) error
	ListCardIssuesByCardID(ctx context.Context, cardID pgtype.UUID) ([]CardIssue, error)
	ListCardOptionsByCardID(ctx context.Context, cardID pgtype.UUID) ([]CardOption, error)
	ListCardTableColumnsByCardID(ctx context.Context, cardID pgtype.UUID) ([]CardTableColumn, error)
	ListCardTableItemsByCardID(ctx context.Context, cardID pgtype.UUID) ([]ListCardTableItemsByCardIDRow, error)
	ListCardsBySetID(ctx context.Context, setID pgtype.UUID) ([]Card, error)
	ListSetsByUserID(ctx context.Context, creatorID int64) ([]ListSetsByUserIDRow, error)
	RecordCardReview(ctx context.Context, arg RecordCardReviewParams) (CardReview, error)
	UpdateCardByID(ctx context.Context, arg UpdateCardByIDParams) (Card, error)
	UpsertCardProgress(ctx context.Context, arg UpsertCardProgressParams) (UserCardProgress, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
