// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordAnswerResult = `-- name: RecordAnswerResult :one
INSERT INTO answer_results (user_id, card_id, correct, answered_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, card_id, correct, answered_at, created_at
`

type RecordAnswerResultParams struct {
	UserID     int64              `json:"user_id"`
	CardID     pgtype.UUID        `json:"card_id"`
	Correct    bool               `json:"correct"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

func (q *Queries) RecordAnswerResult(ctx context.Context, arg RecordAnswerResultParams) (AnswerResult, error) {
	row := q.db.QueryRow(ctx, recordAnswerResult,
		arg.UserID,
		arg.CardID,
		arg.Correct,
		arg.AnsweredAt,
	)
	var i AnswerResult
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.Correct,
		&i.AnsweredAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateFactProgressOnAnswer = `-- name: UpdateFactProgressOnAnswer :one
INSERT INTO user_fact_progress (
    user_id,
    fact_id,
    elo,
    ceiling_found,
    consecutive_correct,
    consecutive_incorrect,
    interval_days,
    ease_factor,
    next_review_at,
    last_reviewed_at
)
VALUES (
    $1,
    $2,
    CASE WHEN $3::BOOLEAN THEN 700 + 201 ELSE GREATEST(400, 700 - 201) END,
    CASE WHEN NOT $3::BOOLEAN THEN TRUE ELSE FALSE END,
    CASE WHEN $3::BOOLEAN THEN 1 ELSE 0 END,
    CASE WHEN NOT $3::BOOLEAN THEN 1 ELSE 0 END,
    0,
    2.50,
    CASE WHEN NOT $3::BOOLEAN THEN CURRENT_TIMESTAMP + INTERVAL '1 day' ELSE CURRENT_TIMESTAMP END,
    CURRENT_TIMESTAMP
)
ON CONFLICT (user_id, fact_id) DO UPDATE SET
    elo = CASE
        WHEN $3::BOOLEAN THEN user_fact_progress.elo + 201
        ELSE GREATEST(400, user_fact_progress.elo - 201)
    END,
    ceiling_found = CASE
        WHEN NOT $3::BOOLEAN OR user_fact_progress.ceiling_found OR (user_fact_progress.elo + 201 >= 1400) THEN TRUE
        ELSE FALSE
    END,
    consecutive_correct = CASE
        WHEN $3::BOOLEAN THEN user_fact_progress.consecutive_correct + 1
        ELSE 0
    END,
    consecutive_incorrect = CASE
        WHEN NOT $3::BOOLEAN THEN user_fact_progress.consecutive_incorrect + 1
        ELSE 0
    END,
    ease_factor = CASE
        WHEN NOT $3::BOOLEAN THEN GREATEST(1.30, user_fact_progress.ease_factor - 0.20)
        ELSE user_fact_progress.ease_factor
    END,
    interval_days = CASE
        WHEN $3::BOOLEAN AND NOT (NOT $3::BOOLEAN OR user_fact_progress.ceiling_found OR (user_fact_progress.elo + 201 >= 1400)) THEN 0
        WHEN NOT $3::BOOLEAN THEN 1
        WHEN user_fact_progress.interval_days = 0 THEN 1
        WHEN user_fact_progress.interval_days = 1 THEN 3
        ELSE LEAST(30, (user_fact_progress.interval_days * user_fact_progress.ease_factor)::INT)
    END,
    next_review_at = CASE
        WHEN $3::BOOLEAN AND NOT (NOT $3::BOOLEAN OR user_fact_progress.ceiling_found OR (user_fact_progress.elo + 201 >= 1400)) THEN CURRENT_TIMESTAMP
        WHEN NOT $3::BOOLEAN THEN CURRENT_TIMESTAMP + INTERVAL '1 day'
        WHEN user_fact_progress.interval_days = 0 THEN CURRENT_TIMESTAMP + INTERVAL '1 day'
        WHEN user_fact_progress.interval_days = 1 THEN CURRENT_TIMESTAMP + INTERVAL '3 days'
        ELSE CURRENT_TIMESTAMP + (LEAST(30, (user_fact_progress.interval_days * user_fact_progress.ease_factor)::INT) || ' days')::INTERVAL
    END,
    last_reviewed_at = CURRENT_TIMESTAMP
RETURNING user_id, fact_id, elo, ceiling_found, consecutive_correct, consecutive_incorrect, interval_days, ease_factor, next_review_at, last_reviewed_at
`

type UpdateFactProgressOnAnswerParams struct {
	UserID  int64  `json:"user_id"`
	FactID  string `json:"fact_id"`
	Column3 bool   `json:"column_3"`
}

func (q *Queries) UpdateFactProgressOnAnswer(ctx context.Context, arg UpdateFactProgressOnAnswerParams) (UserFactProgress, error) {
	row := q.db.QueryRow(ctx, updateFactProgressOnAnswer, arg.UserID, arg.FactID, arg.Column3)
	var i UserFactProgress
	err := row.Scan(
		&i.UserID,
		&i.FactID,
		&i.Elo,
		&i.CeilingFound,
		&i.ConsecutiveCorrect,
		&i.ConsecutiveIncorrect,
		&i.IntervalDays,
		&i.EaseFactor,
		&i.NextReviewAt,
		&i.LastReviewedAt,
	)
	return i, err
}
