// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTotalDueCardsForUser = `-- name: CountTotalDueCardsForUser :one
SELECT COUNT(*)::INT AS due_count
FROM facts f
JOIN user_sets us ON us.set_id = f.set_id AND us.user_id = $1
LEFT JOIN user_fact_progress ufp ON ufp.fact_id = f.id AND ufp.user_id = $1
WHERE ufp.next_review_at IS NULL OR ufp.next_review_at <= NOW()
`

func (q *Queries) CountTotalDueCardsForUser(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countTotalDueCardsForUser, userID)
	var due_count int32
	err := row.Scan(&due_count)
	return due_count, err
}

const createSet = `-- name: CreateSet :one
INSERT INTO sets (title, author_id, share_code)
VALUES ($1, $2, $3)
RETURNING id, title, author_id, share_code, created_at, updated_at
`

type CreateSetParams struct {
	Title     string `json:"title"`
	AuthorID  int64  `json:"author_id"`
	ShareCode string `json:"share_code"`
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (Set, error) {
	row := q.db.QueryRow(ctx, createSet, arg.Title, arg.AuthorID, arg.ShareCode)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.ShareCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSet = `-- name: DeleteSet :execrows
DELETE FROM sets WHERE id = $1 AND author_id = $2
`

type DeleteSetParams struct {
	ID       pgtype.UUID `json:"id"`
	AuthorID int64       `json:"author_id"`
}

func (q *Queries) DeleteSet(ctx context.Context, arg DeleteSetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSet, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNextReviewDateForUser = `-- name: GetNextReviewDateForUser :one
SELECT MIN(ufp.next_review_at)::TIMESTAMPTZ AS next_review_at
FROM facts f
JOIN user_sets us ON us.set_id = f.set_id AND us.user_id = $1
JOIN user_fact_progress ufp ON ufp.fact_id = f.id AND ufp.user_id = $1
WHERE ufp.next_review_at > NOW()
`

func (q *Queries) GetNextReviewDateForUser(ctx context.Context, userID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getNextReviewDateForUser, userID)
	var next_review_at pgtype.Timestamptz
	err := row.Scan(&next_review_at)
	return next_review_at, err
}

const getSetByID = `-- name: GetSetByID :one
SELECT
    s.id,
    s.title,
    s.author_id,
    u.first_name AS author_first_name,
    u.last_name AS author_last_name,
    u.username AS author_username,
    s.share_code,
    s.created_at,
    s.updated_at,
    (SELECT COUNT(*)::INT FROM cards c JOIN facts f ON c.fact_id = f.id WHERE f.set_id = s.id) AS cards_total,
    (SELECT COUNT(*)::INT
     FROM facts f
     LEFT JOIN user_fact_progress ufp ON ufp.fact_id = f.id AND ufp.user_id = $2
     WHERE f.set_id = s.id
       AND (ufp.next_review_at IS NULL OR ufp.next_review_at <= NOW())) AS cards_due
FROM sets s
JOIN users u ON s.author_id = u.id
WHERE s.id = $1
  AND (s.author_id = $2 OR EXISTS (SELECT 1 FROM user_sets us WHERE us.set_id = s.id AND us.user_id = $2))
`

type GetSetByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID int64       `json:"user_id"`
}

type GetSetByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	AuthorID        int64              `json:"author_id"`
	AuthorFirstName string             `json:"author_first_name"`
	AuthorLastName  pgtype.Text        `json:"author_last_name"`
	AuthorUsername  pgtype.Text        `json:"author_username"`
	ShareCode       string             `json:"share_code"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CardsTotal      int32              `json:"cards_total"`
	CardsDue        int32              `json:"cards_due"`
}

func (q *Queries) GetSetByID(ctx context.Context, arg GetSetByIDParams) (GetSetByIDRow, error) {
	row := q.db.QueryRow(ctx, getSetByID, arg.ID, arg.UserID)
	var i GetSetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.AuthorFirstName,
		&i.AuthorLastName,
		&i.AuthorUsername,
		&i.ShareCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardsTotal,
		&i.CardsDue,
	)
	return i, err
}

const getSetByShareCode = `-- name: GetSetByShareCode :one
SELECT
    s.id,
    s.title,
    s.author_id,
    u.first_name AS author_first_name,
    u.last_name AS author_last_name,
    u.username AS author_username,
    s.share_code,
    s.created_at,
    s.updated_at,
    (SELECT COUNT(*)::INT FROM cards c JOIN facts f ON c.fact_id = f.id WHERE f.set_id = s.id) AS cards_total,
    (SELECT COUNT(*)::INT
     FROM facts f
     LEFT JOIN user_fact_progress ufp ON ufp.fact_id = f.id AND ufp.user_id = $2
     WHERE f.set_id = s.id
       AND (ufp.next_review_at IS NULL OR ufp.next_review_at <= NOW())) AS cards_due
FROM sets s
JOIN users u ON s.author_id = u.id
WHERE s.share_code = $1
`

type GetSetByShareCodeParams struct {
	ShareCode string `json:"share_code"`
	UserID    int64  `json:"user_id"`
}

type GetSetByShareCodeRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	AuthorID        int64              `json:"author_id"`
	AuthorFirstName string             `json:"author_first_name"`
	AuthorLastName  pgtype.Text        `json:"author_last_name"`
	AuthorUsername  pgtype.Text        `json:"author_username"`
	ShareCode       string             `json:"share_code"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CardsTotal      int32              `json:"cards_total"`
	CardsDue        int32              `json:"cards_due"`
}

func (q *Queries) GetSetByShareCode(ctx context.Context, arg GetSetByShareCodeParams) (GetSetByShareCodeRow, error) {
	row := q.db.QueryRow(ctx, getSetByShareCode, arg.ShareCode, arg.UserID)
	var i GetSetByShareCodeRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.AuthorFirstName,
		&i.AuthorLastName,
		&i.AuthorUsername,
		&i.ShareCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardsTotal,
		&i.CardsDue,
	)
	return i, err
}

const getSetLeaderboard = `-- name: GetSetLeaderboard :many
WITH set_facts AS (
    SELECT f.id FROM facts f WHERE f.set_id = $1::UUID
),
facts_count AS (
    SELECT COUNT(*)::INT AS total FROM set_facts
),
participants AS (
    SELECT us.user_id FROM user_sets us WHERE us.set_id = $1::UUID
    UNION
    SELECT s.author_id AS user_id FROM sets s WHERE s.id = $1::UUID
),
user_scores AS (
    SELECT
        p.user_id,
        fc.total AS facts_count,
        CASE
            WHEN fc.total = 0 THEN 0::FLOAT
            ELSE COALESCE(SUM(COALESCE(ufp.elo, 700)), 0)::FLOAT / fc.total
        END AS avg_elo
    FROM participants p
    CROSS JOIN facts_count fc
    LEFT JOIN set_facts sf ON TRUE
    LEFT JOIN user_fact_progress ufp ON ufp.user_id = p.user_id AND ufp.fact_id = sf.id
    GROUP BY p.user_id, fc.total
),
ranked AS (
    SELECT
        us.user_id,
        u.first_name,
        u.last_name,
        u.username,
        CASE
            WHEN us.facts_count = 0 THEN 0
            WHEN us.avg_elo <= 800 THEN 0
            WHEN us.avg_elo >= 1400 THEN 100
            ELSE ROUND(((us.avg_elo - 800.0) / 600.0) * 100)::INT
        END AS percentile,
        RANK() OVER (ORDER BY us.avg_elo DESC)::INT AS rank
    FROM user_scores us
    JOIN users u ON u.id = us.user_id
)
SELECT user_id, first_name, last_name, username, percentile, rank
FROM ranked
ORDER BY rank ASC, user_id ASC
`

type GetSetLeaderboardRow struct {
	UserID     int64       `json:"user_id"`
	FirstName  string      `json:"first_name"`
	LastName   pgtype.Text `json:"last_name"`
	Username   pgtype.Text `json:"username"`
	Percentile int32       `json:"percentile"`
	Rank       int32       `json:"rank"`
}

func (q *Queries) GetSetLeaderboard(ctx context.Context, setID pgtype.UUID) ([]GetSetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getSetLeaderboard, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSetLeaderboardRow
	for rows.Next() {
		var i GetSetLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Percentile,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSetRating = `-- name: GetUserSetRating :one
WITH set_facts AS (
    SELECT f.id FROM facts f WHERE f.set_id = $2::UUID
),
facts_count AS (
    SELECT COUNT(*)::INT AS total FROM set_facts
),
participants AS (
    SELECT us.user_id FROM user_sets us WHERE us.set_id = $2::UUID
    UNION
    SELECT s.author_id AS user_id FROM sets s WHERE s.id = $2::UUID
    UNION
    SELECT $1::BIGINT AS user_id
),
user_scores AS (
    SELECT
        p.user_id,
        fc.total AS facts_count,
        CASE
            WHEN fc.total = 0 THEN 0::FLOAT
            ELSE COALESCE(SUM(COALESCE(ufp.elo, 700)), 0)::FLOAT / fc.total
        END AS avg_elo
    FROM participants p
    CROSS JOIN facts_count fc
    LEFT JOIN set_facts sf ON TRUE
    LEFT JOIN user_fact_progress ufp ON ufp.user_id = p.user_id AND ufp.fact_id = sf.id
    GROUP BY p.user_id, fc.total
),
ranked AS (
    SELECT
        us.user_id,
        CASE
            WHEN us.facts_count = 0 THEN 0
            WHEN us.avg_elo <= 800 THEN 0
            WHEN us.avg_elo >= 1400 THEN 100
            ELSE ROUND(((us.avg_elo - 800.0) / 600.0) * 100)::INT
        END AS percentile,
        RANK() OVER (ORDER BY us.avg_elo DESC)::INT AS rank
    FROM user_scores us
    JOIN users u ON u.id = us.user_id
)
SELECT percentile, rank
FROM ranked
WHERE user_id = $1::BIGINT
`

type GetUserSetRatingParams struct {
	UserID int64       `json:"user_id"`
	SetID  pgtype.UUID `json:"set_id"`
}

type GetUserSetRatingRow struct {
	Percentile int32 `json:"percentile"`
	Rank       int32 `json:"rank"`
}

func (q *Queries) GetUserSetRating(ctx context.Context, arg GetUserSetRatingParams) (GetUserSetRatingRow, error) {
	row := q.db.QueryRow(ctx, getUserSetRating, arg.UserID, arg.SetID)
	var i GetUserSetRatingRow
	err := row.Scan(&i.Percentile, &i.Rank)
	return i, err
}

const getUserSets = `-- name: GetUserSets :many
SELECT
    s.id,
    s.title,
    s.author_id,
    u.first_name AS author_first_name,
    u.last_name AS author_last_name,
    u.username AS author_username,
    s.share_code,
    s.created_at,
    s.updated_at,
    (SELECT COUNT(*)::INT FROM cards c JOIN facts f ON c.fact_id = f.id WHERE f.set_id = s.id) AS cards_total,
    (SELECT COUNT(*)::INT
     FROM facts f
     LEFT JOIN user_fact_progress ufp ON ufp.fact_id = f.id AND ufp.user_id = $1
     WHERE f.set_id = s.id
       AND (ufp.next_review_at IS NULL OR ufp.next_review_at <= NOW())) AS cards_due
FROM user_sets us
JOIN sets s ON us.set_id = s.id
JOIN users u ON s.author_id = u.id
WHERE us.user_id = $1
ORDER BY us.joined_at DESC
`

type GetUserSetsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	AuthorID        int64              `json:"author_id"`
	AuthorFirstName string             `json:"author_first_name"`
	AuthorLastName  pgtype.Text        `json:"author_last_name"`
	AuthorUsername  pgtype.Text        `json:"author_username"`
	ShareCode       string             `json:"share_code"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CardsTotal      int32              `json:"cards_total"`
	CardsDue        int32              `json:"cards_due"`
}

func (q *Queries) GetUserSets(ctx context.Context, userID int64) ([]GetUserSetsRow, error) {
	rows, err := q.db.Query(ctx, getUserSets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSetsRow
	for rows.Next() {
		var i GetUserSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.AuthorFirstName,
			&i.AuthorLastName,
			&i.AuthorUsername,
			&i.ShareCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CardsTotal,
			&i.CardsDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isSetAuthor = `-- name: IsSetAuthor :one
SELECT EXISTS(
    SELECT 1 FROM sets WHERE id = $1 AND author_id = $2
) AS is_author
`

type IsSetAuthorParams struct {
	ID       pgtype.UUID `json:"id"`
	AuthorID int64       `json:"author_id"`
}

func (q *Queries) IsSetAuthor(ctx context.Context, arg IsSetAuthorParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSetAuthor, arg.ID, arg.AuthorID)
	var is_author bool
	err := row.Scan(&is_author)
	return is_author, err
}

const joinSet = `-- name: JoinSet :one
INSERT INTO user_sets (user_id, set_id)
VALUES ($1, $2)
ON CONFLICT (user_id, set_id) DO UPDATE SET joined_at = user_sets.joined_at
RETURNING user_id, set_id, joined_at
`

type JoinSetParams struct {
	UserID int64       `json:"user_id"`
	SetID  pgtype.UUID `json:"set_id"`
}

func (q *Queries) JoinSet(ctx context.Context, arg JoinSetParams) (UserSet, error) {
	row := q.db.QueryRow(ctx, joinSet, arg.UserID, arg.SetID)
	var i UserSet
	err := row.Scan(&i.UserID, &i.SetID, &i.JoinedAt)
	return i, err
}

const leaveSet = `-- name: LeaveSet :execrows
DELETE FROM user_sets WHERE set_id = $1 AND user_id = $2
`

type LeaveSetParams struct {
	SetID  pgtype.UUID `json:"set_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) LeaveSet(ctx context.Context, arg LeaveSetParams) (int64, error) {
	result, err := q.db.Exec(ctx, leaveSet, arg.SetID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
