// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const countUserActiveDays = `-- name: CountUserActiveDays :one
SELECT COUNT(DISTINCT DATE(answered_at))::INT AS active_days
FROM answer_results
WHERE user_id = $1 AND answered_at >= NOW() - INTERVAL '7 days'
`

func (q *Queries) CountUserActiveDays(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countUserActiveDays, userID)
	var active_days int32
	err := row.Scan(&active_days)
	return active_days, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, created_at, last_active_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, name, last_active_at)
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    last_active_at = CURRENT_TIMESTAMP
RETURNING id, name, created_at, last_active_at
`

type UpsertUserParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}
